### ISSUE TITLE
Optional arguments

### ISSUE THREAD

**Issue by pitchart** [mnapoli/fluent-symfony#19]
There are two ways to manage optional dependencies in symfony described [here](https://symfony.com/doc/current/service_container/optional_dependencies.html)

Once created a Reference's invalid behavior can not be modified.

What about two functions like `nullIfMissing('service_id')` and `ignoreIfMissing('service_id')` that could be used like the `get()` function to create a Reference with the appropriate invalidBehavior parameter ?

**Comment by mnapoli** [comment]
What about a new argument to `get`: `get($serviceId, $optional)`? E.g. `get('service_id', true)`

**Comment by rejinka** [comment]
`get('service_id', true)` does not really reads like the desired behavior.

:+1: for ` nullIfMissing('service_id')`.

**Comment by pitchart** [comment]
The 2 behaviors (`nullIfMissing` and `ignoreIfMissing`) are linked to ContainerInterface constants : 

* ContainerInterface::NULL_ON_INVALID_REFERENCE
* ContainerInterface::IGNORE_ON_INVALID_REFERENCE

That's why i proposed those 2 functions.
We could also use a second argument for the `get()` function but in this case we should maybe create an enum class to be more expressive, like `InvalidReference::null()` and `InvalidReference::ignore()` ?

**Comment by mnapoli** [comment]
I don't understand where `nullIfMissing()` would be used:

- `get(nullIfMissing('id'))`
- or `nullIfMissing('id')` (i.e. replaces `get()`)

?

I find the second one really not clear at all, the first one is OK but having to nest things too much gets a bit weird IMO.

Here is another idea: `get('id')->nullIfMissing()` and `get('id')->ignoreIfMissing()`

**Comment by pitchart** [comment]
The `Reference` objects can not be modified, so we can not have `get(nullIfMissing('id'))`.

We can try the `get('id')->nullIfMissing()` but we will need to maintain our `Reference` class to make it an immutable class.

**Comment by mnapoli** [comment]
:+1: it should be pretty easy to have our own `Reference` class that implements `DefinitionHelper` I guess

**Comment by mnapoli** [comment]
Closed by #26
