### ISSUE TITLE
Support for decorated services

### ISSUE THREAD

**Issue by pitchart** [mnapoli/fluent-symfony#20]
The goal of this feature is to be able to override an existing definition, but keep having acces to the old one, as described here :
https://symfony.com/doc/current/service_container/service_decoration.html

I've started to work on a `decorate($entryId, $renameId, $priority)` method for the create definition helper.

Interested ?

**Comment by rejinka** [comment]
Small issue (but that could also be only a thing to me): How about change the order of the first two parameters? Feels more natural to me to first name the service, you're defining.

**Comment by pitchart** [comment]
The second parameter is not the name of the definition, but the new name for the old definition, and it's not a mandatory parameter.

In fact a complete syntax should be `create('decorator_service')->decorate('decorated_service', 'decorator_service.decorated', 2)`.

I have added documentation examples in the PR.
