### ISSUE TITLE
Support for private aliases

### ISSUE THREAD

**Issue by stof** [mnapoli/fluent-symfony#21]
Currently, the alias helper can only register public aliases. Private aliases should be supported too.

**Comment by rejinka** [comment]
How about following

```php
return [
    'alias_for_some_service' => alias('some_service')
        ->private(),
];
```

We have the same syntax for `create()`, i think this would be straight forward. But as `Definition` and `Alias` don't share an interface, we'd have nearly the same code in `AliasDefinitionHelper` as in `CreateDefinitionHelper`.

**Comment by stof** [comment]
yeah, this seems fine.

Alias only has the public vs private config, so it is logical to not share an interface

**Comment by mnapoli** [comment]
Done in #22, thanks!
