### ISSUE TITLE
Factory configurable class name

### ISSUE THREAD

**Issue by judgedim** [mnapoli/fluent-symfony#28]
I've tried to use compilation for service which created by factory, but got error

```php

return [
    'config' => factory([ConfigFactory::class, 'create']),
];

```

`Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\RuntimeException: Please add the class to service "config" even if it is constructed by a factory since we might need to add method calls based on compile-time checks. in /vendor/symfony/dependency-injection/Compiler/CheckDefinitionValidityPass.php on line 49`

also I've found in [documentation](http://symfony.com/doc/current/service_container/factories.html):

>  When using a factory to create services, the value chosen for the class option has no effect on the resulting service. The actual class name only depends on the object that is returned by the factory. However, the configured class name may be used by compiler passes and therefore should be set to a sensible value.

I think that we can add class name as second optional argument for factory, e.g.

```php

return [
    'config' => factory([ConfigFactory::class, 'create'], Config::class),
];

```

@mnapoli what do you think ? Or I missed something ?

**Comment by mnapoli** [comment]
Oh yeah that's a good point. However I don't understand why [this test](https://github.com/mnapoli/fluent-symfony/blob/master/tests/FactoryTest.php#L20) does not fail then :/ ?

Which version of Symfony are you using? Or maybe it's because we don't compile the container (and it seems it's a compilation pass that does the check, so compilation passes are not called if the container is not compiled…).

**Comment by judgedim** [comment]
I use symfony/dependency-injection: v3.2.4

yes, this [test](https://github.com/mnapoli/fluent-symfony/blob/master/tests/FactoryTest.php#L20) does not cover it because we don't use compilation

**Comment by mnapoli** [comment]
I've reproduced the problem by always compiling the container in tests: #29

I'll be looking into a solution in a separate pull request so that the diff is readable on its own.

**Comment by mnapoli** [comment]
#30 should fix this bug.

**Comment by mnapoli** [comment]
Thanks for the report!
