### ISSUE TITLE
Migrate to PHPUnit 6.0

### ISSUE THREAD

**Issue by mnapoli** [mnapoli/fluent-symfony#9]
PHPUnit 6 has been released, let's try it out here.

Needs to be done once #4 is merged to avoid unnecessary conflicts.

**Comment by rejinka** [comment]
Prepared a branch, nothing to doooo this weekend ;-)

**Comment by mnapoli** [comment]
Great, FYI I've enabled Travis CI so there's CI now

**Comment by rejinka** [comment]
Yeah, noticed that 👍
